### ISSUE TITLE
modify examples file

### ISSUE THREAD

**Issue by poccariswet** [poccariswet/apng#15]
like
```toml
[[example]]
name = "sample1"
path = "examples/***.rs"

[[example]]
name = "sample2"
path = "examples/***.rs"
...
```
